{{- if and .Values.common.iam .Values.common.iam.createServiceAccount -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ default (include "zafran-app.serviceAccountName" .) }}
  labels:
    {{- include "zafran-app.labels" . | nindent 4 }}
  {{- with .Values.common.iam }}
  {{- if or .extraAnnotations .awsIamRole }}
  annotations:
  {{- if .awsIamRole }}
    eks.amazonaws.com/role-arn: {{ .awsIamRole }}
  {{- end }}
  {{- if .extraAnnotations }}
    {{- toYaml .extraAnnotations | nindent 4 }}
  {{- end }}
  {{- end }}
  {{- end }}
{{- end }}
