# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "s3" {
    bucket  = "zafran-terraform"
    encrypt = true
    key     = "network/vpc/terraform.tfstate"
    profile = "default-legacy"
    region  = "us-east-2"
  }
}
