name: 'Helm Chart Release'
description: 'Package and upload a Helm chart to S3'
inputs:
  chart-name:
    description: 'Name of the Helm chart'
    required: true
  chart-path:
    description: 'Path to the Helm chart directory'
    required: true
  s3-bucket:
    description: 'S3 bucket name'
    required: true
runs:
  using: 'composite'
  steps:
    - uses: azure/setup-helm@v3
      with:
        version: 'v3.11.1'

    - name: Install Helm S3 Plugin
      run: helm plugin install https://github.com/hypnoglow/helm-s3.git
      shell: bash

    - name: Add Helm S3 Repository
      run: helm repo add my-repo s3://${{ inputs.s3-bucket }}/stable/${{ inputs.chart-name }}
      shell: bash

    - name: Package Helm Chart
      run: helm package ${{ inputs.chart-path }}
      shell: bash

    - name: Push Chart to S3 Bucket
      run: helm s3 push ${{ inputs.chart-name }}-*.tgz my-repo
      shell: bash
