fullnameOverride: ""
nameOverride: ""

github: 
  user: SharonDiskin
  token: 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
  secret: gmfovpurjstkhviiwdijxqjkprdm

orgAllowlist: github.com/ZafranSecurity/*

aws: {}

allowForkPRs: false
allowDraftPRs: false
hidePrevPlanComments: false
hideUnchangedPlanComments: false

image:
  repository: ghcr.io/runatlantis/atlantis
  tag: ""
  pullPolicy: Always

service:
  type: NodePort
  port: 80
  targetPort: 4141

statefulSet:
  securityContext:
    fsGroup: 1000
    runAsUser: 100
    fsGroupChangePolicy: "OnRootMismatch"

ingress:
  enabled: true
  path: /*
  pathType: ImplementationSpecific

resources: {}

atlantisDataDirectory: /atlantis-data

volumeClaim:
  enabled: true
  dataStorage: 5Gi

replicaCount: 1

nodeSelector: {}
tolerations: []  # Set tolerations as an empty array
affinity: {}

livenessProbe:
  enabled: true
  periodSeconds: 60
  initialDelaySeconds: 5
  timeoutSeconds: 5
  successThreshold: 1
  failureThreshold: 5
  scheme: HTTP

readinessProbe:
  enabled: true
  periodSeconds: 60
  initialDelaySeconds: 5
  timeoutSeconds: 5
  successThreshold: 1
  failureThreshold: 5
  scheme: HTTP

initConfig:
  enabled: false
  image: alpine:latest
  imagePullPolicy: IfNotPresent
  # sharedDir is set as env var INIT_SHARED_DIR
  sharedDir: /plugins
  workDir: /tmp
  sizeLimit: 100Mi
  # example of how the script can be configured to install tools/providers required by the atlantis pod
  script: |
    #!/bin/sh
    set -eoux pipefail

    # example for terragrunt
    TG_VERSION="v0.52.1"
    TG_SHA256_SUM="98d45f6bfbfae84b51364c1ad6920f09ecb4d834908b0535e4e331a9fc6fc75b"
    TG_FILE="${INIT_SHARED_DIR}/terragrunt"
    wget https://github.com/gruntwork-io/terragrunt/releases/download/${TG_VERSION}/terragrunt_linux_amd64 -O "${TG_FILE}"
    echo "${TG_SHA256_SUM}  ${TG_FILE}" | sha256sum -c
    chmod 755 "${TG_FILE}"
    terragrunt -v

    # example for terragrunt-atlantis-config
    TAC_VERSION="1.16.0" # without v
    TAC_SHA256_SUM="fc3b069cf4ae51e9b7a7d01f09862d1974b260fffb3ec857d661d7b1756fe26f"
    TAC_FILE="${INIT_SHARED_DIR}/terragrunt-atlantis-config"
    wget "https://github.com/transcend-io/terragrunt-atlantis-config/releases/download/v${TAC_VERSION}/terragrunt-atlantis-config_${TAC_VERSION}_linux_amd64.tar.gz"
    echo "${TAC_SHA256_SUM}  terragrunt-atlantis-config_${TAC_VERSION}_linux_amd64.tar.gz" | sha256sum -c
    tar xf "terragrunt-atlantis-config_${TAC_VERSION}_linux_amd64.tar.gz"
    cp -fv "terragrunt-atlantis-config_${TAC_VERSION}_linux_amd64/terragrunt-atlantis-config_${TAC_VERSION}_linux_amd64" "${TAC_FILE}"
    chmod 755 "${TG_FILE}"
    terragrunt-atlantis-config version

serviceAccount:
  create: true
  mount: true
  name: null

enableKubernetesBackend: false

googleServiceAccountSecrets: []

extraVolumes: []
extraVolumeMounts: []

extraManifests: []

initContainers: []

hostNetwork: false

extraArgs: []

extraContainers: []

containerSecurityContext: {}

servicemonitor:
  enabled: false
  interval: "30s"
  path: /metrics
  auth:
    basicAuth:
      enabled: false
    externalSecret:
      enabled: false

podMonitor:
  enabled: false
  interval: "30s"

lifecycle: {}
