name: 'Helm Chart Release'
description: 'Package and upload a Helm chart to S3'
inputs:
  chart-path:
    description: 'Path to the Helm chart directory'
    required: true
  checkout_to_repo:
    description: 'Repository name to change directory to, if provided'
    required: false
    default: ''
runs:
  using: 'composite'
  steps:
  - name: Bump Chart Version
    run: |
      if [ -n "${{ inputs.checkout_to_repo }}" ]; then
        cd "${{ inputs.checkout_to_repo }}"
      fi
      CHART_FILE="${{ inputs.chart-path }}/Chart.yaml"
      CURRENT_VERSION=$(grep 'version:' $CHART_FILE | awk '{ print $2 }')
      NEW_VERSION=$(echo $CURRENT_VERSION | awk -F. '{ printf "%d.%d.%d", $1, $2, $3+1 }')
      sed -i "s/version: $CURRENT_VERSION/version: $NEW_VERSION/" $CHART_FILE
      git config --global user.email "actions@github.com"
      git config --global user.name "GitHub Actions"
      git add $CHART_FILE
      git commit -m "Bump chart version to $NEW_VERSION"
      git push
    shell: bash
