name: Bump Chart Version Test

on: 
  workflow_dispatch:
  push:
    branches:
      - main  # or any other branch you want to trigger this workflow

jobs:
  bump-chart-version:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Bump Chart Version
        run: |
          CHART_FILE="helm_charts/zafran-app/Chart.yaml"
          CURRENT_VERSION=$(grep 'version:' $CHART_FILE | awk '{ print $2 }')
          NEW_VERSION=$(echo $CURRENT_VERSION | awk -F. '{ printf "%d.%d.%d", $1, $2, $3+1 }')
          sed -i "s/version: $CURRENT_VERSION/version: $NEW_VERSION/" $CHART_FILE
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git add $CHART_FILE
          git commit -m "Bump chart version to $NEW_VERSION"
          git push
