name: Test and Release Helm Charts
on: 
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'kubernetes/helm_charts/zafran-*/**'

jobs:
  release-helm-chart-to-stage:
    runs-on: ubuntu-latest
    environment: stage
    steps:
      - name: Checkout sharon-test repo
        uses: actions/checkout@v4
        with:
          path: 'sharon-test'  
          fetch-depth: 0

      - uses: aws-actions/configure-aws-credentials@v2
        name: Configure AWS credentials
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2

      - name: Zafran-app | Check for changes in a path
        uses: ./sharon-test/.github/actions/check-changes-in-path  
        id: check-zafran-app-path
        with:
          path: 'kubernetes/helm_charts/zafran-app/'
          checkout_to_repo: 'sharon-test'

      - name: Zafran-fe | Check for changes in a path
        uses: ./sharon-test/.github/actions/check-changes-in-path  
        id: check-zafran-fe-path
        with:
          path: 'kubernetes/helm_charts/zafran-fe/'
          checkout_to_repo: 'sharon-test'
          
      - name: Zafran-app | Bump chart version
        if: github.event_name == 'push' && steps.check-zafran-app-path.outputs.changed == 'true'
        uses: ./sharon-test/.github/actions/bump-chart-version
        with:
          chart-path: ${{ vars.HELM_CHART_PATH }}/${{ vars.HELM_CHART_APP }}

      - name: Zafran-app | Release Helm Chart
        if: steps.check-zafran-app-path.outputs.changed == 'true'
        uses: ./sharon-test/.github/actions/helm-chart-release
        with:
          chart-name: ${{ vars.HELM_CHART_APP }}
          chart-path: ${{ vars.HELM_CHART_PATH }}/${{ vars.HELM_CHART_APP }}
          s3-bucket: ${{ vars.HELM_BUCKET }}

      - name: Zafran-fe | Bump chart version
        if: github.event_name == 'push' && steps.check-zafran-fe-path.outputs.changed == 'true'
        uses: ./sharon-test/.github/actions/bump-chart-version
        with:
          chart-path: ${{ vars.HELM_CHART_PATH }}/${{ vars.HELM_CHART_FE }}

      - name: Zafran-fe |  Release Helm Chart 
        if: steps.check-zafran-fe-path.outputs.changed == 'true'
        uses: ./sharon-test/.github/actions/helm-chart-release
        with:
          chart-name: ${{ vars.HELM_CHART_FE }}
          chart-path: ${{ vars.HELM_CHART_PATH }}/${{ vars.HELM_CHART_FE }}
          s3-bucket: ${{ vars.HELM_BUCKET }}
  
