name: Test and Release Helm Charts
on: 
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'kubernetes/helm_charts/zafran-*/**'

jobs:
  release-helm-chart-to-stage:
    runs-on: ubuntu-latest
    environment: stage
    steps:
      - name: Checkout sharon-test repo
        uses: actions/checkout@v4
        with:
          path: 'sharon-test'  
          fetch-depth: 0

      - uses: aws-actions/configure-aws-credentials@v2
        name: Configure AWS credentials
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2
      - name: test
        run: echo "${{ vars.HELM_CHART_PATH }}/${{ vars.HELM_CHART_FE }} "
      
          
      - name: Zafran-app | Bump chart version
        uses: ./sharon-test/.github/actions/bump-chart-version
        with:
          chart-path: ${{ vars.HELM_CHART_PATH }}/${{ vars.HELM_CHART_APP }}
  
