name: Test and Release Helm Charts
on: 
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  test-helm-chart:
    uses: ZafranSecurity/sharon-test/test-helm.yml@main
  
  release-helm-chart:
    runs-on: ubuntu-latest
    steps:
      - uses: aws-actions/configure-aws-credentials@v2
        name: Configure AWS credentials
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2
