name: Helm Chart Testing Workflow

on: [ workflow_dispatch, pull_request, push ]

jobs:
  test-helm-chart:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout infra repo
      uses: actions/checkout@v4
      with:
        ref: ${{ github.head_ref || github.ref }}
        path: 'sharon-test' 

    - uses: aws-actions/configure-aws-credentials@v2
      name: Configure AWS credentials
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-2

    - name: Checkout zafran-app repo
      uses: actions/checkout@v4
      with:
        repository: 'ZafranSecurity/zafran-app'
        token: ${{ secrets.GH_PAT }}
        ref: 'main'
        path: 'zafran-app' 

    - name: Set Context
      run: aws eks --region us-east-2 update-kubeconfig --name zafran-prod-k8s

    - name: Set up Helm
      uses: azure/setup-helm@v3
      with:
        version: 'v3.11.1'

    # - name: Lint Helm Chart
    #   run: helm lint ./sharon-test/helm_charts/zafran-app

    - name: Dry Run Test Helm Charts
      run: |
        for dir in ./zafran-app/deploy/*/ ; do
          if [ -f "$dir/helm_values.yaml" ]; then
            echo "Dry run testing Helm Chart for $dir"
            helm install --dry-run --debug test-release sharon-test/helm_charts/zafran-app -f "./zafran-app/deploy/assets/helm_values.yaml"
            if [ $? -ne 0 ]; then
              echo "Dry run test failed for $dir"
              exit 1
            fi                
          fi
        done
