name: Helm Chart Testing Workflow

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  test-helm-chart:
    runs-on: ubuntu-latest
    steps:
    - name: Set env vars
      run: |
            echo "HELM_CHART_PATH=sharon-test/helm_charts" >> $GITHUB_ENV 
            echo "HELM_SCRIPT_DIR_PATH=sharon-test/.github/scripts" >> $GITHUB_ENV
            echo "HELM_VALUES_DIR_PATH=zafran-app/deploy" >> $GITHUB_ENV
            echo "HELM_CHART_APP=zafran-app" >> $GITHUB_ENV
            echo "HELM_CHART_FE=zafran-fe" >> $GITHUB_ENV

    - name: Checkout infra repo
      uses: actions/checkout@v4
      with:
        ref: ${{ github.head_ref || github.ref }}
        path: 'sharon-test' 

    - name: Checkout zafran-app repo
      uses: actions/checkout@v4
      with:
        repository: 'ZafranSecurity/zafran-app'
        token: ${{ secrets.GH_PAT }}
        ref: 'main'
        path: 'zafran-app' 

    - uses: aws-actions/configure-aws-credentials@v2
      name: Configure AWS credentials
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-2

    - name: Set Context
      run: aws eks --region us-east-2 update-kubeconfig --name zafran-prod-k8s

    - name: Set up Helm
      uses: azure/setup-helm@v3
      with:
        version: 'v3.11.1'

    - name: Install helm diff plugin
      run: helm plugin install https://github.com/databus23/helm-diff

    - name: Install helm unittest plugin
      run: helm plugin install https://github.com/helm-unittest/helm-unittest.git

    - name: Check diff with old release (zafran-app)
      run: |
        for dir in ${{ env.HELM_VALUES_DIR_PATH }}/* ; do
          if [ "$(basename "$dir")" = "fe" ]; then
            continue
          fi
          if [ -f "$dir/helm_values.yaml" ]; then
            ${{ env.HELM_SCRIPT_DIR_PATH }}/helm_diff.sh ${{ env.HELM_CHART_APP }} ${{ env.HELM_CHART_PATH }}/${{ env.HELM_CHART_APP }} $dir/helm_values.yaml 
          fi
        done

    - name: Check diff with old release (zafran-fe)
      run: |
        if [ -f "${{ env.HELM_VALUES_DIR_PATH }}/fe/helm_values.yaml" ]; then
          ${{ env.HELM_SCRIPT_DIR_PATH }}/helm_diff.sh ${{ env.HELM_CHART_FE }} ${{ env.HELM_CHART_PATH }}/${{ env.HELM_CHART_FE }} ${{ env.HELM_VALUES_DIR_PATH }}/fe/helm_values.yaml
        fi

    - name: Execute Helm Unit Tests (Zafran-app)
      run: |
        helm unittest ${{ env.HELM_CHART_PATH }}/${{ env.HELM_CHART_APP }}

    - name: Execute Helm Unit Tests (Zafran-app)
      run: |
        helm unittest ${{ env.HELM_CHART_PATH }}/${{ env.HELM_CHART_FE }}

    - name: Dry Run chart(zafran-app)
      run: |
        for dir in ${{ env.HELM_VALUES_DIR_PATH }}/* ; do
          if [ "$(basename "$dir")" = "fe" ]; then
            continue
          fi
          if [ -f "$dir/helm_values.yaml" ]; then
            ${{ env.HELM_SCRIPT_DIR_PATH }}/helm_dry_run.sh ${{ env.HELM_CHART_APP }} ${{ env.HELM_CHART_PATH }}/${{ env.HELM_CHART_APP }} $dir/helm_values.yaml 
          fi
        done

    - name: Dry Run chart (zafran-fe)
      run: |
        if [ -f "${{ env.HELM_VALUES_DIR_PATH }}/fe/helm_values.yaml" ]; then
          ${{ env.HELM_SCRIPT_DIR_PATH }}/helm_dry_run.sh ${{ env.HELM_CHART_FE }} ${{ env.HELM_CHART_PATH }}/${{ env.HELM_CHART_FE }} ${{ env.HELM_VALUES_DIR_PATH }}/fe/helm_values.yaml
        fi
